name: Metrics

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Naingui74
          committer_branch: main
          filename: github-metrics.svg

          # sections de base (on garde lÃ©ger)
          template: classic
          base: header, activity, metadata
          config_timezone: Europe/Paris

          # ğŸ”¹ GitHub Skyline (3D contributions)
          plugin_skyline: yes
          plugin_skyline_year: 2024
          plugin_skyline_compatibility: yes

          # ğŸ”¹ Achievements compacts
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact

          # âŒ pas de barres de langages
          plugin_languages: no