name: Metrics

on:
  # Mise à jour automatique tous les jours à 01h
  schedule:
    - cron: "0 1 * * *"
  # Lancer manuellement depuis l’onglet Actions
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          # Ton token stocké en secret
          token: ${{ secrets.METRICS_TOKEN }}

          # Ton user
          user: Naingui74

          # Fichier de sortie dans le repo
          filename: github-metrics.svg

          # Template + sections de base
          template: classic
          base: header, activity, community, repositories, metadata

          # Plugins sympas (tu peux en enlever si tu veux)
          config_timezone: Europe/Paris
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact